### ISSUE TITLE
How many variant callers can be used with vaxrank?

### ISSUE THREAD

**Issue by davidroberson** [openvax/vaxrank#167]
We may try to run an ensemble approach to get the somatic calls.  Thank you

**Comment by julia326** [comment]
@davidroberson You can use vaxrank with any number of VCFs - it supports taking a union of variants from multiple somatic variant callers. The `--vcf` argument is repeated, so you can invoke vaxrank with:
```
vaxrank --vcf <vcf1> --vcf <vcf2> --bam <tumor RNA BAM> ...
```
