### ISSUE TITLE
A way from VCF format to mutated peptides only

### ISSUE THREAD

**Issue by nishuai** [openvax/vaxrank#187]
Hi Alex,

Thank you for developing Vaxrank, your pipeline is the earliest and most easy-to-use pipeline for antigenic peptide prediction I have seen so far!

I wonder is there a way for me to use only part of your code to generate mutated peptides of some certain length, we would like to have peptide sequences to have a look at the general properties surrounding the mutated sites.

Thank you for your help.

Best

**Comment by armish** [comment]
Hi @nishuai,

If I am understanding your question right, [varcode](https://github.com/openvax/varcode), which `vaxrank` depends on, should give you that functionality. The [README](https://github.com/openvax/varcode/blob/master/README.md) and [this probably a bit out-dated notebook](https://github.com/openvax/varcode/blob/master/examples/varcode-quick_start.ipynb) should help you get started.

Hope this helps.

**Comment by nishuai** [comment]
Hi @armish ,

That's great, it seems to be exactly what I am looking for, thank you very much 👍
