### ISSUE TITLE
Add unit tests for generating HTML/ASCII/PDF reports

### ISSUE THREAD

**Issue by iskandr** [openvax/vaxrank#24]

**Comment by iskandr** [comment]
I added HTML and CSV output generation (accidentally pushed to master). We should add ASCII (and maybe PDF) and then check that all reports contain the same vaccine peptides.

**Comment by iskandr** [comment]
@julia326 We're now testing the report code, right?

**Comment by ihodes** [comment]
@julia326 can we close this issue now?
