### ISSUE TITLE
Different location text

### ISSUE THREAD

**Issue by ihodes** [openvax/vaxrank#67]
Right now they look like  `chr2 g.36768911G>T`, but this is difficult to read and hard to copy/paste into IGV. How would `chr2:36768911 G>T` work?

**Comment by julia326** [comment]
To clarify: do you mean the ASCII report template?

**Comment by ihodes** [comment]
Yes! (And also the PDF? I think it uses the same thing.)

**Comment by iskandr** [comment]
I'll just note that this deviates from [HGVS](http://www.hgvs.org/mutnomen/examplesDNA.html#sub) but I don't actually care, I find the latter notation easier to read.

**Comment by ihodes** [comment]
Is there an advantage to sticking with the "official" notation?

**Comment by iskandr** [comment]
How do you represent variants like "chr17 g.5365710_5365711insGTGG"?

**Comment by ihodes** [comment]
ch17:5365710 G>GTGG ?

**Comment by iskandr** [comment]
Works for me, we can just show the VCF nucleotides.

**Comment by julia326** [comment]
Going to change these in the CSV format since that's just for our use; also considering the "simple-text" to be a duplicate of this issue.
